// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Entidades;

public partial class MovimientosContext : DbContext
{
    public MovimientosContext(DbContextOptions<MovimientosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Cuenta> Cuentas { get; set; }

    public virtual DbSet<Movimiento> Movimientos { get; set; }

    public virtual DbSet<Persona> Personas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.ClienteId).HasName("PK_CLIENTES");

            entity.ToTable("Clientes", "Mov", tb => tb.HasComment("Tabla de Clientes"));

            entity.Property(e => e.ClienteId).HasComment("Identificador de la tabla Clientes");
            entity.Property(e => e.Contrasena).HasComment("Contraseña");
            entity.Property(e => e.Estado).HasComment("Estado del Cliente");
            entity.Property(e => e.PersonaId).HasComment("Identificador de la tabla Persona");

            entity.HasOne(d => d.Persona).WithMany(p => p.Clientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CLIENTES_REF_CLIEN_PERSONAS");
        });

        modelBuilder.Entity<Cuenta>(entity =>
        {
            entity.HasKey(e => e.CuentaId).HasName("PK_CUENTAS");

            entity.ToTable("Cuentas", "Mov", tb => tb.HasComment("Tabla de Cuentas"));

            entity.Property(e => e.CuentaId).HasComment("Identificador de la tabla Cuentas");
            entity.Property(e => e.ClienteId).HasComment("Identificador de la tabla Clientes");
            entity.Property(e => e.Estado).HasComment("Estado de la cuenta");
            entity.Property(e => e.NumeroCuenta).HasComment("Numero de cuenta");
            entity.Property(e => e.SaldoInicial).HasComment("Saldo inicial");
            entity.Property(e => e.TipoCuenta).HasComment("Tipo de Cuenta");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Cuenta).HasConstraintName("FK_CUENTAS_REF_CUENT_CLIENTES");
        });

        modelBuilder.Entity<Movimiento>(entity =>
        {
            entity.HasKey(e => e.MovimientoId).HasName("PK_MOVIMIENTOS");

            entity.ToTable("Movimientos", "Mov", tb => tb.HasComment("Tabla de Movimientos"));

            entity.Property(e => e.MovimientoId).HasComment("Identificador de la Tabla Movimiento");
            entity.Property(e => e.CuentaId).HasComment("Identificador de la tabla Cuentas");
            entity.Property(e => e.Fecha).HasComment("Fecha de registro");
            entity.Property(e => e.Saldo).HasComment("Saldo despues del movimiento");
            entity.Property(e => e.TipoMovimiento).HasComment("Tipo de Movimiento");
            entity.Property(e => e.Valor).HasComment("Valor del movimiento");

            entity.HasOne(d => d.Cuenta).WithMany(p => p.Movimientos).HasConstraintName("FK_MOVIMIEN_REF_MOVIM_CUENTAS");
        });

        modelBuilder.Entity<Persona>(entity =>
        {
            entity.HasKey(e => e.PersonaId).HasName("PK_PERSONAS");

            entity.ToTable("Personas", "Mov", tb => tb.HasComment("Tabla de Personas"));

            entity.Property(e => e.PersonaId).HasComment("Identificador de la tabla Persona");
            entity.Property(e => e.Direccion).HasComment("Direccion de la persona");
            entity.Property(e => e.Edad).HasComment("Edad");
            entity.Property(e => e.Genero).HasComment("Descripcion del genero");
            entity.Property(e => e.Identificacion).HasComment("Identificacion");
            entity.Property(e => e.Nombre).HasComment("Descripcion del nombre");
            entity.Property(e => e.Telefono).HasComment("Telefono de la persona");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}