// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entidades;

/// <summary>
/// Tabla de Clientes
/// </summary>
[Table("Clientes", Schema = "Mov")]
public partial class Cliente
{
    /// <summary>
    /// Identificador de la tabla Clientes
    /// </summary>
    [Key]
    [Column("Cliente_Id")]
    public long ClienteId { get; set; }

    /// <summary>
    /// Identificador de la tabla Persona
    /// </summary>
    [Column("Persona_Id")]
    public long PersonaId { get; set; }

    /// <summary>
    /// Contraseña
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Contrasena { get; set; }

    /// <summary>
    /// Estado del Cliente
    /// </summary>
    public bool? Estado { get; set; }

    [InverseProperty("Cliente")]
    public virtual ICollection<Cuenta> Cuenta { get; set; } = new List<Cuenta>();

    [ForeignKey("PersonaId")]
    [InverseProperty("Clientes")]
    public virtual Persona Persona { get; set; }
}