// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entidades;

/// <summary>
/// Tabla de Cuentas
/// </summary>
[Table("Cuentas", Schema = "Mov")]
public partial class Cuenta
{
    /// <summary>
    /// Identificador de la tabla Cuentas
    /// </summary>
    [Key]
    [Column("Cuenta_Id")]
    public long CuentaId { get; set; }

    /// <summary>
    /// Identificador de la tabla Clientes
    /// </summary>
    [Column("Cliente_Id")]
    public long? ClienteId { get; set; }

    /// <summary>
    /// Numero de cuenta
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string NumeroCuenta { get; set; }

    /// <summary>
    /// Tipo de Cuenta
    /// </summary>
    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string TipoCuenta { get; set; }

    /// <summary>
    /// Saldo inicial
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal SaldoInicial { get; set; }

    /// <summary>
    /// Estado de la cuenta
    /// </summary>
    public bool Estado { get; set; }

    [ForeignKey("ClienteId")]
    [InverseProperty("Cuenta")]
    public virtual Cliente Cliente { get; set; }

    [InverseProperty("Cuenta")]
    public virtual ICollection<Movimiento> Movimientos { get; set; } = new List<Movimiento>();
}