// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entidades;

/// <summary>
/// Tabla de Movimientos
/// </summary>
[Table("Movimientos", Schema = "Mov")]
public partial class Movimiento
{
    /// <summary>
    /// Identificador de la Tabla Movimiento
    /// </summary>
    [Key]
    [Column("Movimiento_Id")]
    public long MovimientoId { get; set; }

    /// <summary>
    /// Identificador de la tabla Cuentas
    /// </summary>
    [Column("Cuenta_Id")]
    public long? CuentaId { get; set; }

    /// <summary>
    /// Fecha de registro
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    /// <summary>
    /// Tipo de Movimiento
    /// </summary>
    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string TipoMovimiento { get; set; }

    /// <summary>
    /// Valor del movimiento
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal Valor { get; set; }

    /// <summary>
    /// Saldo despues del movimiento
    /// </summary>
    [Column(TypeName = "decimal(18, 2)")]
    public decimal Saldo { get; set; }

    [ForeignKey("CuentaId")]
    [InverseProperty("Movimientos")]
    public virtual Cuenta Cuenta { get; set; }
}