// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entidades;

/// <summary>
/// Tabla de Personas
/// </summary>
[Table("Personas", Schema = "Mov")]
[Index("Identificacion", Name = "Persona_IDX02", IsUnique = true)]
public partial class Persona
{
    /// <summary>
    /// Identificador de la tabla Persona
    /// </summary>
    [Key]
    [Column("Persona_Id")]
    public long PersonaId { get; set; }

    /// <summary>
    /// Descripcion del nombre
    /// </summary>
    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nombre { get; set; }

    /// <summary>
    /// Descripcion del genero
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Genero { get; set; }

    /// <summary>
    /// Edad
    /// </summary>
    public int Edad { get; set; }

    /// <summary>
    /// Identificacion
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Identificacion { get; set; }

    /// <summary>
    /// Direccion de la persona
    /// </summary>
    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Direccion { get; set; }

    /// <summary>
    /// Telefono de la persona
    /// </summary>
    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Telefono { get; set; }

    [InverseProperty("Persona")]
    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();
}